### ISSUE TITLE
can't charge after shut down the tablet

### ISSUE THREAD

**Issue by max20091** [latte-dev/android_kernel_xiaomi_latte#1]
I think this is related to the kernel.
Steps to reproduce:
1. Shut down the tablet
2. Plug the charger in
3. Stuck at MI logo

**Comment by tank0412** [comment]
I think that it is a defconfig fault because it works on prebuilt kernel

**Comment by harrynowl** [comment]
Fixed from my test with commit [a166d7f55a1dee7a5b85126d8985e9e4ab2913d3](https://github.com/latte-dev/android_device_xiaomi_latte/commit/a166d7f55a1dee7a5b85126d8985e9e4ab2913d3).
