### ISSUE TITLE
2.24 Ghz should be called OC frequency instead of Base frequency

### ISSUE THREAD

**Issue by max20091** [latte-dev/android_kernel_xiaomi_latte#2]
According to Intel ARK, 2.24 Ghz is maximum OC frequency and by default kernel will use this frequency, this will damage the CPU so I suggest just limit the CPU to 1.44 Ghz and leave the higher frequency as extended option.

**Comment by tank0412** [comment]
Anyway, on stock xiaomi rom maximum frequency is 2.24 ghs so i think that this frequency is OK.

**Comment by harrynowl** [comment]
No.

Intel turbo boost is based on meeting power and thermal conditions and it will dynamically adjust the frequency up to this point to meet that goal. These parameters are defined within the microcode.

**Comment by max20091** [comment]
So what I see in Kernel Adiutor is just illusion? Isn't we can force the CPU to run at 2.24Ghz without needing turbo boost? I think it's also related to the kernel, not just the BIOS
And also Turbo Boost is just some kind of "safe OC" technology and what I see here it doesn't work well on Android and allow us to set always turbo boost to maximum frequency (idk why)

**Comment by max20091** [comment]
Just confirmed that my tablet still run at 2.24Ghz although it is very, very hot and my screen is flickering due to not enough voltage then it drop to 0% battery and my tablet shutted down => Turbo Boost control doesn't work on Android
Confirmed while using Lineage OS build 2/03 and Intel Performance Viewer app (This app was removed from Google Play, however you can find it on APKPure)
