### ISSUE TITLE
Issues after kernel rebase

### ISSUE THREAD

**Issue by tank0412** [latte-dev/android_kernel_xiaomi_latte#3]
Hi, there.
https://github.com/latte-dev/android_kernel_xiaomi_latte/tree/cm-13.0-rebase
DMESG:
https://gist.github.com/tank0412/d25769d43e47d9e75a696de09995545d
What works:
wifi, bt, lcd, touchscreen
What is dead:
sensors, brightness, random reboots (but rarer than on cm-13.0-rebase2 branch)
NOTE: It goes to deep sleep, but sometimes only!

https://github.com/latte-dev/android_kernel_xiaomi_latte/tree/cm-13.0-rebase2
What works:
bt, lcd, touchscreen
What is dead:
WIFI (working but cases reboots), sensors, brightness, many random reboots!
NOTE: It goes to deep sleep, but sometimes only!

I need help. Thanks.

**Comment by thatsthat** [comment]
I know it's been a long time, but was the battery problems solved and if so were can I find the working kernel?
